apiVersion: v1
kind: Service
metadata:
  name: fluentd
  labels:
    component: fluentd
spec:
  selector:
    component: fluentd
  ports:
    -
      name: l-tcp
      nodePort: 30111
      port: 80
      protocol: TCP
      targetPort: tcp
    -
      name: l-udp
      nodePort: 30222
      port: 80
      protocol: UDP
      targetPort: udp
  type: NodePort
