apiVersion: v1
kind: Service
metadata:
  name: kibana
  labels:
    component: kibana
spec:
  selector:
    component: kibana
  ports:
    -
      nodePort: 30560
      port: 80
      protocol: TCP
      targetPort: http
  type: NodePort
